version: 1
database settings:
    db: pessto_marshall_sandbox
    host: localhost
    user: pessto
    password: p355t0

apache prefix: ""

eso archive credentials:
    username: nbd
    password: 31bAR07
 
nttarchiver:
    path to dropbox folder: "/Users/Dave/git_repos/pessto_marshall_engine/pessto_marshall_engine/tests/input/data/marshall_dropbox"
    path to archive root folder: "/tmp/marshall_archive"
    ## past number of days to check for new data (keep at a few days in case new data was added or there is a delay getting data into the eso archive)
    download window size: 4

downloads:
    transient cache directory: "/Users/Dave/git_repos/marshall_webapp/marshall_webapp/static/caches/transients/"

stats cache directory: "/Users/Dave/git_repos/marshall_webapp/marshall_webapp/static/caches/stats/"

main css filepath: "/marshall/static/styles/css/main_marshall.css"
main js filepath: "/marshall/static/js/main-ck.js"
path to webapp icon: "/marshall/static/images/pessto_icon.png"

asassn settings:
    discoveries google sheet id: "1A9NOjQTS4nSt_KSb0YUTlQ0utTARjcGT5UWbsADcY1M#gid=0"
    sn plain text: "http://www.astronomy.ohio-state.edu/~assassin/sn_list.txt"
    transients html page: "http://www.astronomy.ohio-state.edu/~assassin/transients.html"

## webapp secrets
secrets:
    authn policy: "a^h34**92"

tns_cookie: "SESSf11000adb2f9f9d356be78e0a49b286d=kmGMbfeo8GRIBjBPy-vnD5q9c96kvLvzFhlWVZ_D27c; Drupal.tableDrag.showWeight=0; has_js=1"

credentials:
    lsq:
        username: lsq
        password: schmidteso
    ps1-3pi:
        username: ps13pi
        password: fgss
    ps1-md:
        username: ps1sc
        password: skysurveys
    ps1-fgss:
        username: ps1sc
        password: skysurveys
    ps1-gw:
        username: psnsc
        password: "!gravity"
    skymapper:
        username: pessto
        password: "!explosions"
    google_drive:
        username: d.r.young@qub.ac.uk
        password: "i8VLH)+d7rm}22o9P;W%&yRa7pmu7P"

panstarrs urls:
    3pi:
        summary csv: "http://star.pst.qub.ac.uk/sne/ps13pi/site_media/images/lightcurves/summary.csv"
        recurrence csv: "http://star.pst.qub.ac.uk/sne/ps13pi/site_media/images/lightcurves/recurrences.csv"
    gw:
        summary csv: http://star.pst.qub.ac.uk/sne/ps1gw/site_media/images/lightcurves/summary.csv
        recurrence csv: http://star.pst.qub.ac.uk/sne/ps1gw/site_media/images/lightcurves/recurrences.csv

lsq urls:
    summary csv: "http://portal.nersc.gov/project/lssn/test/ryan/adb/pessto/candidates.csv"
    recurrence csv: "http://portal.nersc.gov/project/lssn/test/ryan/adb/pessto/candidates_obs.csv"

master sne url: "http://observ.pereplet.ru/sn_e.html"
tocp url: "http://www.cbat.eps.harvard.edu/unconf/tocp.html"
des sne url: "https://portal.nersc.gov/des-sn/transients/"

bright sn list urls:
    date ordered list: "http://www.rochesterastronomy.org/snimages/sndate.html"
    main page: "http://www.rochesterastronomy.org/supernova.html"

exports:
    path to pessto classifications csv export: "/Users/Dave/git_repos/pessto_marshall_engine/pessto_marshall_engine/database/export/tests/output/pessto_classifications_export_01.csv"
    path to pessto object sumarraies for wiserep sql export: "/tmp/wiserep.sql"

logging settings:
    formatters:
        file_style:
            format: '* %(asctime)s - %(name)s - %(levelname)s (%(pathname)s > %(funcName)s > %(lineno)d) - %(message)s  '
            datefmt: '%Y/%m/%d %H:%M:%S'
        console_style:
            format: '* %(asctime)s - %(levelname)s: %(pathname)s:%(funcName)s:%(lineno)d > %(message)s'
            datefmt: '%H:%M:%S'
        html_style:
            format: '<div id="row" class="%(levelname)s"><span class="date">%(asctime)s</span>   <span class="label">file:</span><span class="filename">%(filename)s</span>   <span class="label">method:</span><span class="funcName">%(funcName)s</span>   <span class="label">line#:</span><span class="lineno">%(lineno)d</span> <span class="pathname">%(pathname)s</span>  <div class="right"><span class="message">%(message)s</span><span class="levelname">%(levelname)s</span></div></div>'
            datefmt: '%Y-%m-%d <span class= "time">%H:%M <span class= "seconds">%Ss</span></span>'
    handlers:
        console:
            class: logging.StreamHandler
            level: DEBUG
            formatter: console_style
            stream: ext://sys.stdout
        file:
            class: logging.handlers.GroupWriteRotatingFileHandler
            level: WARNING
            formatter: file_style
            filename: /Users/Dave/git_repos/pessto_webapp/logs/marshall.log
            mode: w+
            maxBytes: 102400
            backupCount: 1
            # class: logging.FileHandler
            # level: DEBUG
            # formatter: file_style
            # filename: /Users/Dave/git_repos/pessto_webapp/logs/marshall.log
            # mode: w
        debug_file:
            class: logging.handlers.GroupWriteRotatingFileHandler
            level: DEBUG
            formatter: file_style
            filename: /Users/Dave/git_repos/pessto_webapp/logs/marshall_debug.log
            mode: w+
            maxBytes: 1024000
            backupCount: 3
        html_log_file:
            # class: logging.handlers.GroupWriteRotatingFileHandler
            # level: DEBUG
            # formatter: html_style
            # filename: /Users/Dave/Dropbox/bitbucket_projects/pessto_marshall/webpages/document_root/pessto/private/marshall/logs/log.html
            # mode: w+
            # maxBytes: 102400
            # backupCount: 3
            class: logging.FileHandler
            level: INFO
            formatter: html_style
            filename: /Users/Dave/git_repos/pessto_webapp/logs/marshall_log.html
            mode: w
        # html_debug_file:
        #     class: logging.handlers.GroupWriteRotatingFileHandler
        #     formatter: html_style
        #     level: WARNING
        #     filename: /Users/Dave/Dropbox/bitbucket_projects/pessto_marshall/webpages/document_root/pessto/private/marshall/logs/log_debug.html
        #     mode: w+
            # maxBytes: 1024000
            # backupCount: 3
    root:
        level: ERROR
        # handlers: [debug_file,file,html_log_file]
        handlers: [file,console,html_log_file]
