source _archive_faint_sources_in_inbox.sql
source _set_currentFilename_in_database.sql
source _update_archivePaths.sql
source _update_filetype_calibration_and_reduction_stage_keywords.sql
source _update_filetype_and_instrument_keys.sql
source _update_file_associations_set_esophaseIII_and_ssdr_flags.sql
source _update_fluxerr_and_photzper_keywords.sql
source _update_sofi_effective_gain_and_readnoise.sql
source _update_maglim_magsat_for_images.sql
source _update_origin_keyword.sql
source _update_sofi_exptime_keywords.sql
source _update_spec_sys_keyword_in_spectra.sql
source _update_SPEC_RES_values_for_efosc_spectra.sql
source _update_spec_bin_keywords_for_spectra.sql
source _update_prodcatg.sql
source _update_bunit_for_2df_spectra.sql
source _update_obid1_column.sql
source _remove_crap_acquisition_images.sql
source _set_currentFilename_in_database.sql
source _update_archivePaths.sql
source _remove_dat_from_standard_object_names.sql
source _update_efosc_imaging_issue_comments.sql
source _update_efosc_imaging_issue_comments.sql
source __miscellaneous_fixes.sql



